ALTER TABLE "Address"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Order"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "OrderItems"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
